const validQueryParams = [
  "shoulders",
  "chest",
  "lower arms",
  "waist",
  "back",
  "upper legs",
  "neck",
  "cardio",
  "upper arms",
  "lower legs",
  "abs",
  "upper back",
  "adductors",
  "delts",
  "levator scapulae",
  "traps",
  "hamstrings",
  "abductors",
  "pectorals",
  "quads",
  "triceps",
  "spine",
  "biceps",
  "cardiovascular system",
  "forearms",
  "serratus anterior",
  "calves",
  "glutes",
  "lats",
  "bosu ball",
  "cable",
  "stability ball",
  "stepmill machine",
  "smith machine",
  "ez barbell",
  "hammer",
  "medicine ball",
  "body weight",
  "wheel roller",
  "kettlebell",
  "assisted",
  "stationary bike",
  "tire",
  "resistance band",
  "trap bar",
  "barbell",
  "upper body ergometer",
  "dumbbell",
  "leverage machine",
  "skierg machine",
  "sled machine",
  "band",
  "elliptical machine",
  "olympic barbell",
  "roller",
  "rope",
  "weighted",
];

module.exports = validQueryParams;
